### PR TITLE
Minimum viable packaging

### LINKED ISSUE #8: %install_ext is deprecated...
IPython deprecated the `%install_ext` magic (https://github.com/ipython/ipython/issues/8634). The replacement story is using a package to distribute the extension and then use `%load_ext package.extension` to load the extension.

Ah, and shamless plug: if you don't want to work with your own package, there is also now https://github.com/ipython-contrib/IPython-extensions watermark would be a great addition there!

### PR DESCRIPTION
**Pull request by pjbull**
Move some things around to make watermark installable as a package.

Took the `setup.py` from PyPI. Should fix #8

### CODE REVIEW

**Comment by pjbull** [comment]
Also, you should be able to test with:
`pip install -e git+https://github.com/pjbull/watermark#egg=watermark`

screen shot 2016-05-21 at 1 41 49 pm

**Comment by rasbt** [comment]
Wow, this is great, thank you so much for this pull request. This has been sitting on my todo list for a long time!

**Comment by pjbull** [comment]
:+1: Thanks for putting together watermark. I gave it a shout out in a talk I gave and got chided by a Jupyter dev for still using `%install_ext`, so I figured I'd do my part!

**Comment by rasbt** [comment]
Yeah, I should have fixed this way earlier, it's kind of embarrassing, sorry! Glad to hear that you find it useful though, and thanks again for the fix! Btw. I also uploaded it to PyPI now so that it can be installed via a simple `pip install watermark`.

Cheers,
Sebastian

**Comment by pjbull** [comment]
Brilliant! I'll update for the version of the talk I'm giving tomorrow:
https://github.com/pjbull/data-science-is-software/blob/master/notebooks/data-science-is-software-talk.ipynb

**Comment by rasbt** [comment]
This looks really nice, good luck with the talk :)

**Comment by jonsedar** [comment]
Thanks for that @pjbull (and thanks of course @rasbt for creating this in the first place!). I've only recently started using watermark and find it especially useful when using packages that are still in rapid development e.g. [PyMC3](https://github.com/pymc-devs/pymc3)

Very nice to have PyPi installation :)

**Pull request merged**
