### PR TITLE
v1.5

### PR DESCRIPTION
**Pull request by rasbt**

### CODE REVIEW

**Comment by iamaziz** [comment]
My bad! I forgot to update README.md with the new option.

**Comment by rasbt** [comment]
Oh, no worries! I wanted to ping you about that, but then I thought I would make a new release version anyway and could address while I am at it :). Thanks so much for your contribution :)

**Comment by iamaziz** [comment]
I already made the update, but then before I push the PR button I saw your PR. Then I said hold on a minute :-)

**Comment by rasbt** [comment]
sry about the confusion! I should have said sth, my bad

**Pull request merged**
